// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW1vUnpy1LRTepMazmv6VS7T2TyDgj_Dk',
    appId: '1:790957298562:android:04ef5ed62563e9cfc2b59b',
    messagingSenderId: '790957298562',
    projectId: 'insurance-hero-app',
    storageBucket: 'insurance-hero-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8qQ7U8mtc1_dCBV0o615eSvRStBtK-pQ',
    appId: '1:790957298562:ios:59f008bc23584524c2b59b',
    messagingSenderId: '790957298562',
    projectId: 'insurance-hero-app',
    storageBucket: 'insurance-hero-app.appspot.com',
    iosClientId: '790957298562-nce45tti34p41eju62q0ei3nfappmqod.apps.googleusercontent.com',
    iosBundleId: 'com.app.developlogix.insurancehero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8qQ7U8mtc1_dCBV0o615eSvRStBtK-pQ',
    appId: '1:790957298562:ios:59f008bc23584524c2b59b',
    messagingSenderId: '790957298562',
    projectId: 'insurance-hero-app',
    storageBucket: 'insurance-hero-app.appspot.com',
    iosClientId: '790957298562-nce45tti34p41eju62q0ei3nfappmqod.apps.googleusercontent.com',
    iosBundleId: 'com.app.developlogix.insurancehero',
  );
}
